export const icons = {
  home: '🏠',
  search: '🔍',
  download: '📥',
  watchlist: '❤️',
  watchlistEmpty: '🤍',
  profile: '👤',
  play: '▶',
  info: 'ℹ️',
  settings: '⚙️',
  close: '✕',
  reload: '🔄',
  delete: '🗑️',
  movie: '🎬',
  empty: '📂',
  error: '⚠️',
  star: '⭐',
  arrowRight: '▶',
  arrowDown: '▼',
};
